apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mh
  template:
    metadata:
      labels:
        app: mh
    spec:
      containers:
      - name: mh
        image: acrscaleinfinite.azurecr.io/mh:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: mh-service
spec:
  selector:
    app: mh
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer